---
apiVersion: v1
kind: Namespace
metadata:
  name: octops-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: octops-broadcaster-http
  namespace: octops-system
  labels:
    app: octops-broadcaster-http
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: octops-broadcaster-http
  labels:
    app: octops-broadcaster-http
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "watch"]
  - apiGroups: ["agones.dev"]
    resources: ["gameservers", "fleets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: octops-broadcaster-http
  labels:
    app: octops-broadcaster-http
subjects:
  - kind: User
    name: system:serviceaccount:octops-system:octops-broadcaster-http
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: octops-broadcaster-http
---
apiVersion: v1
kind: Service
metadata:
  name: octops-broadcaster-http
  namespace: octops-system
spec:
  selector:
    app: octops-broadcaster-http
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: octops-broadcaster-http
  namespace: octops-system
  labels:
    app: octops-broadcaster-http
spec:
  selector:
    matchLabels:
      app: octops-broadcaster-http
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: octops-broadcaster-http
    spec:
      serviceAccountName: octops-broadcaster-http
      containers:
        - name: controller
          image: octops/agones-broadcaster-http:v0.2.0-alpha
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
